name: CI/CD

on:
  push:
    branches: 
      - develop
jobs:
  func-build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: OpenFaaS build and push
        uses: mrsimpson/action-openfaas-build@master
        with:
          # The OpenFaaS function definition file
          stack-file: homepage.yml
          # Your docker username with push authorization
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          # Your docker username with push authorization
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          # the platform abbreviations to build for, e. g. linux/amd64,linux/arm/v7
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          # Whether the built image shall be deployed (false=no, true=yes)
          # deploy: ${{ github.ref == 'refs/heads/develop' }}
          # OpenFaaS gateway URL (http(s)://my-public-gateway.tld)
          openfaas-gateway: ${{ secrets.OPENFAAS_GATEWAY }}
          # User for authenticating at OpenFaaS gateway
          openfaas-username: ${{ secrets.OPENFAAS_USERNAME }}
          # Password for authenticating at OpenFaaS gateway
          openfaas-password: ${{ secrets.OPENFAAS_PASSWORD }}
      - 
        name: Define ENV VARS
        id: define_env
        run:  echo "::set-output name=github-sha-short::$(echo $GITHUB_SHA | cut -c 1-7)"
      -
        name: Pull template
        uses: docker://openfaas/faas-cli:latest-root
        with:
          # args: template store pull ruby-http
          args: faas template pull https://github.com/openfaas-incubator/ruby-http
      -
        name: Run shrinkwrap build
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: build -f homepage.yml --shrinkwrap
      -
        name: Login to OpenFaaS Gateway
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: login -u ${{ secrets.OPENFAAS_USERNAME}} \
                      -p ${{ secrets.OPENFAAS_PASSWORD }} \
                      -g ${{ secrets.OPENFAAS_GATEWAY }}
      - 
        name: Deploy the function
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: deploy -f homepage.yml --tag sha 
